language: cpp

compiler: g++

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gcc-5 g++-5 cdbs cmake libmsgpack-dev binutils-dev aptitude valgrind ruby1.9.1 ruby1.9.1-dev rubygems1.9.1 irb1.9.1 ri1.9.1 libopenssl-ruby1.9.1 libssl-dev zlib1g-dev rdoc1.9.1 build-essential
  - wget -O - http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.gz/download | tar zxf -
  - pushd boost_1_58_0
  - sudo ./bootstrap.sh --with-libraries=system,filesystem,test --prefix=/usr/local
  - sudo ./b2 install -d0
  - sudo sh -c 'echo "/usr/local/lib" /etc/ld.so.conf.d/local.conf'
  - sudo ldconfig
  - popd
  - sudo aptitude search boost
  - sudo pip install codecov
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz -O - | tar zxf -
  - sudo make -C lcov-1.11/ install
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  - sudo update-alternatives --install /usr/bin/ruby ruby /usr/bin/ruby1.9.1 400 --slave /usr/share/man/man1/ruby.1.gz ruby.1.gz /usr/share/man/man1/ruby1.9.1.1.gz --slave /usr/bin/ri ri /usr/bin/ri1.9.1 --slave /usr/bin/irb irb /usr/bin/irb1.9.1 --slave /usr/bin/rdoc rdoc /usr/bin/rdoc1.9.1

script:
  - cmake -DCMAKE_BUILD_TYPE=Coverage
  - make
  - make test ARGS="-V"
  - make coverage
  - sudo make install

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.info