language: cpp

compiler: g++

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gcc-4.9 g++-4.9
  - sudo apt-get install binutils-dev libboost-all-dev aptitude
  - aptitude search boost
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90

before_script: if [ ! -d "build" ]; then mkdir build; fi;

script: pushd build && cmake .. && make && make test ARGS="-V" && popd
